# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        WebShopBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_EDITOR]
        ROLE_EDITOR: [ROLE_USER]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity: { class: WebShopBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - web_shop.security.login_form_authenticator
            logout:
                path: /logout

    access_control:
        - { path: ^/login, allow_if: "!is_fully_authenticated()" }
        - { path: ^/register, allow_if: "!is_fully_authenticated()" }
