services:
    web_shop.security.login_form_authenticator:
        class: WebShopBundle\Security\LoginFormAuthenticator
        autowire: true
        calls:
            - [createAuthenticatedToken, ['@security.user.provider.in_memory.user', '@?']]
            - [getUser, ['@?', '@security.user.provider.ldap']]
            - [checkCredentials, ['@?', '@security.user.provider.in_memory.user']]

    web_shop.doctrine.hash_password_listener:
        class: WebShopBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    # Twig
    web_shop.twig.web_shop_extension:
        class: WebShopBundle\Twig\WebShopExtension
        calls:
            - [initRuntime, ['@twig']]
        tags:
            - { name: twig.extension }