<?php

namespace WebShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends EntityRepository
{

    public function getNonEmptyCategories()
    {
        return $this->createQueryBuilder("cats")
            ->join("cats.products", "products")
            ->orderBy("cats.name", "ASC")
            ->getQuery()
            ->execute();
    }
}
