<?php

namespace WebShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends EntityRepository
{
    public function getNonEmptyCategories()
    {
        return $this->createQueryBuilder("product_category")
            ->join("product_category.products", "products")
            ->addSelect("products")
            ->orderBy("product_category.name", "ASC")
            ->getQuery()
            ->execute();
    }

    /**
     * @return QueryBuilder
     */
    public function findByQueryBuilder()
    {
        return $this->createQueryBuilder("product_category")
            ->join("product_category.products", "products")
            ->addSelect("products");
    }
}
