<?php

namespace WebShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WebShopBundle\Entity\ProductCategory;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findLastProducts($numberOfProducts)
    {
        return $this->createQueryBuilder("product")
            ->andWhere("product.quantity > 0")
            ->setMaxResults($numberOfProducts)
            ->orderBy("product.id", "desc")
            ->getQuery()
            ->execute();
    }

    public function findByQueryBuilder()
    {
        return $this->createQueryBuilder("product")
            ->where("product.quantity > 0");
    }

    public function findAllByCategoryQueryBuilder(ProductCategory $category)
    {
        return $this->createQueryBuilder("product")
            ->where("product.quantity > 0")
            ->andWhere("product.category = :cat")
            ->setParameter("cat", $category);
    }
}
