<?php

namespace WebShopBundle\Repository;

/**
 * ProductsOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
