<?php

namespace WebShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WebShopBundle\Entity\ProductCategory;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findByQueryBuilder()
    {
        return $this->createQueryBuilder("product");
    }

    public function findAllByCategoryQueryBuilder(ProductCategory $category)
    {
        return $this->createQueryBuilder("product")
            ->where("product.category = :cat")
            ->setParameter("cat", $category);
    }
}
