<?php

namespace WebShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function findNotExpiredQueryBuilder()
    {
        return $this->createQueryBuilder("promotion")
            ->join("promotion.products", "products")
            ->addSelect("products")
            ->andWhere("promotion.endDate >= :now")
            ->andWhere("promotion.startDate <= :now")
            ->setParameter("now", new \DateTime("now"));
    }

    /**
     * @return QueryBuilder
     */
    public function findByQueryBuilder()
    {
        return $this->createQueryBuilder("promotion")
            ->join("promotion.products", "products")
            ->addSelect("products");
    }
}
