<?php

namespace WebShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
    public function findNotExpired()
    {
        return $this->createQueryBuilder("promo")
            ->andWhere("promo.endDate >= :now")
            ->andWhere("promo.startDate <= :now")
            ->setParameter("now", new \DateTime("now"))
            ->getQuery()
            ->execute();
    }
}
